blogpost/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Post urls."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/create',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='posts/<int:id>',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/<int:id>/delete',
        view=views.DeletePostView.as_view(),
        name='delete'
    ),
    path(
        route='posts/<int:id>/update',
        view=views.UpdatePostView.as_view(),
        name='update'
    ),
    path(
        route='posts/<int:id>/comments',
        view=views.AddCommentView.as_view(),
        name='comment'
    ),
    path(
        route='posts/<int:id>/like',
        view=views.LikeView,
        name='like'
    )
]

posts/models.py
"""Post models."""

# Django
from django.db import models

# Models
from django.contrib.auth.models import User

class Post(models.Model):
    """Post model"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile =  models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    picture = models.ImageField(upload_to='posts/pictures')

    resume = models.CharField(max_length=255)

    content = models.TextField()

    like = models.ManyToManyField(User, related_name='like')
    likes = models.PositiveIntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return user and title."""
        return '{} by @ {}'.format(self.title, self.user.username)

class Comment(models.Model):
    """Comments model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    content = models.CharField(max_length=255)

    def __str__(self):
        return 'comment by @{}'.format(self.user.username)
    

posts/forms.py
"""Posts forms."""

# Django
from django import forms

# Models 
from posts.models import Post

class CreatePostForm(forms.ModelForm):
    """Create post form."""

    class Meta:
        """Meta class."""
        model = Post
        fields = (
            'user',
            'profile',
            'title',
            'picture',
            'resume',
            'content'
        )



    

posts/views.py
"""Posts views."""

# Django 
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin

# Views 
from django.views.generic import (
    DetailView,
    CreateView,
    ListView,
    DeleteView,
    UpdateView,
)

# Forms
from posts.forms import CreatePostForm

# Models
from posts.models import Post, Comment
from users.models import Profile
from django.contrib.auth.models import User


class CreatePostView(LoginRequiredMixin, CreateView):
    """Create post view."""
    template_name = 'posts/create.html'
    form_class = CreatePostForm

    def get_success_url(self):
        return reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        """Add user and profile to the context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile 
        return context

    def post(self, request, *args, **kwargs):
        """added 1 to blog_posted counter of the user"""
        profile = Profile.objects.get(user__username=self.request.user.username)
        profile.blog_posted += 1
        profile.save()
        return super().post(request, *args, **kwargs)

class PostFeedView(LoginRequiredMixin, ListView):
    """Return all published posts."""

    template_name = 'posts/feed.html'
    model = Post
    ordering = ('created',)
    paginate_by = 30
    context_object_name = 'posts'

    def get_queryset(self):
        """Filter the posts by the users that the requesting user
        is following and his own posts."""
        
        user = self.request.user
        id_list = []
        follow_list = list(user.follow.all())

        for i in follow_list:
            id_list.append(i.id)
        id_list.append(user.id)

        return Post.objects.filter(user_id__in=id_list)
    

class PostDetailView(LoginRequiredMixin, DetailView):
    """Post detail view. return a especific post."""

    template_name = 'posts/detail.html'
    
    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def get_context_data(self, **kwargs):
        """add likes and comments to the context."""
        context = super().get_context_data(**kwargs)
        id_ = self.kwargs.get("id")
        post = Post.objects.get(pk=id_)

        """Check if the user already liked the post."""
        liked = False
        if post.like.filter(id=self.request.user.id).exists():
            liked = True

        context['liked'] = liked
        context["comments"] = post.comment_set.all()
        return context
    

class DeletePostView(LoginRequiredMixin, DeleteView):
    """Delete post view."""
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:feed')

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def post(self, request, *args, **kwargs):
        """subtract 1 from the blog_posted counter of the user."""  
        username = self.request.user.username
        profile = Profile.objects.get(user__username=username)
        profile.blog_posted -= 1
        profile.save()
        return self.delete(request, *args, **kwargs)
        

class UpdatePostView(LoginRequiredMixin, UpdateView):
    """Update post view."""
    template_name = 'posts/create.html'
    form_class = CreatePostForm
    success_url = reverse_lazy('posts:feed')

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def get_context_data(self, **kwargs):
        """Add user and profile to the context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile 
        return context

class AddCommentView(LoginRequiredMixin, CreateView):
    """Add comment view."""
    template_name = 'comments/new.html'
    model = Comment
    fields = ['user', 'profile', 'post', 'content']

    def get_object(self):
        """Get post id."""
        id_ = self.kwargs.get("id")
        return get_object_or_404(Post, id=id_)

    def get_context_data(self, **kwargs):
        """add users, profile and post to the context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['profile'] = self.request.user.profile
        id_ = self.kwargs.get("id")
        context['post'] = Post.objects.get(pk=id_)   
        return context

    def get_success_url(self):
        id_ = self.kwargs.get("id")
        return reverse('posts:detail', kwargs={'id': id_})
    

def LikeView(request, id):
    """Like view."""

    """Get the especific post."""
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False

    """Check if the user already liked the post."""
    if post.like.filter(id=request.user.id).exists():
        post.like.remove(request.user)
        liked = False
        post.likes -= 1
        post.save()

    else:
        post.like.add(request.user)
        liked = True
        post.likes += 1
        post.save()

    return HttpResponseRedirect(reverse('posts:detail', kwargs={'id': request.POST.get('post_id')})) 

templates/posts/create.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Create a new post!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# title field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                            value="{% if form.title.value %}{{ form.title.value }}{% endif %}"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Picture field #}
                    <div class="form-group mt-4">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.picture.errors %}is-invalid{% endif %}"
                            type="file"
                            name="picture"
                            placeholder="Picture"
                            value="{{ form.picture.value }}"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.picture.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Resume field #}
                    <div class="form-group mt-4">
                        <label>Resume:</label>
                        <input
                            class="form-control {% if form.resume.errors %}is-invalid{% endif %}"
                            type="text"
                            name="resume"
                            placeholder="resume"
                            value="{% if form.resume.value %}{{ form.resume.value }}{% endif %}"
                        > 
                        <div class="invalid-feedback">
                            {% for error in form.resume.errors %}{{ error }}{% endfor %}
                        </div>  
                    </div>

                    <div class="form-group mt-4">
                        <label>Content:</label>
                        <textarea 
                            class="form-control {% if form.content.errors %}is-invalid{% endif %}" 
                            name="content" 
                        >{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>
                    </div>

                    <button type="submit" class="btn btn-secondary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/delete.html
{% extends "base.html" %}

{% block head_content %}
<title>BlogPost | Delete</title>
{% endblock %}

{% block container %}
    <form action="{% url 'posts:delete' post.id %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col">
                <h2>You really want to delete this post {{ post.title }}?</h2>
            </div>
        </div>
    
        <div class="d-grid">
            <input type="submit" class="btn btn-lg btn-secondary mt-5" value="yes">
            <a href="{% url 'posts:feed' %}" class="btn btn-lg btn-secondary mt-3">Cancel</a>
        </div>

    </form>
{% endblock %}

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/detail_card.html" %}
            
        </div>
    </div>

{% endblock %}

templates/posts/detail_card.html
{% load static %}
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    
    
    <div class="card  pt-3 pl-3 pb-1" style="border: 0px;">
        <div class="row d-flex align-items-center g-0">
            <div class="col-1">
                <a href="{% url "users:detail" post.user.username %}">
                    {% if post.profile.picture %}
                    <img class=" rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    {% else %}
                    <img src="{% static 'images/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    {% endif %}
                </a>  
            </div>

            <div class="col">
                <div class="card-body">
                    <p class="mb-0">{{ post.user.get_full_name  }}</p>
                </div>
            </div>
        </div>

    <img style="width: 100%;" src="{{ post.picture.url }}" alt="{{ post.title }}">
    
    <div class="row">
        <p class="col-6"><strong>{{ post.resume }}</strong></p>
        <p class="col-3 offset-md-3"><strong>Likes: {{ post.likes }}</strong></p>
    </div>

    <div class="col-12">
        <p>{{ post.content }}</p>
    </div>

    <div class="col-12">
        {% for comment in comments %}
            {% include "comments/comments_card.html" %}
        {% endfor %}
    </div>
    <div class="row">

        <div class="col-6">
            <a href="{% url 'posts:comment' post.id %}" class="btn btn-lg btn-secondary mt-5">Add comment</a> 
        </div>
        <div class="col-6">
            <form action="{% url 'posts:like' post.id %}" method="POST">
                {% csrf_token %}
                
                {% if liked %}

                    <button class="btn btn-lg btn-danger mt-5 " type="submit" name="post_id" value="{{ post.id }}">
                        Unlike
                    </button>

                {% else %}

                    <button class="btn btn-lg btn-secondary mt-5 " type="submit" name="post_id" value="{{ post.id }}">
                        Like
                    </button>

                {% endif %}
            </form>
        </div>
    </div>
</div>

templates/posts/feed.html
{% extends "base.html" %}

{% block head_content %}
    <title>BlogPost</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">

            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}
        </div>
    </div>



{% endblock %}

templates/posts/post_card.html
{% load static %}
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    
    
    <div class="card  pt-3 pl-3 pb-1" style="border: 0px;">
        <div class="row d-flex align-items-center g-0">
            <div class="col-1">
                <a href="{% url "users:detail" post.user.username %}">
                    {% if post.profile.picture %}
                    <img class=" rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    {% else %}
                    <img src="{% static 'images/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    {% endif %}
                </a>  
            </div>

            <div class="col-8">
                <div class="card-body mt-4">
                    <p>{{ post.user.get_full_name  }}</p>
                </div>
            </div>
            {% if request.user == post.user %}
            <div class="col-2">
                <a href="{% url 'posts:delete' post.id %}" class="btn  btn-secondary mt-3">Delete</a> 
            </div>
            <div class="col-1">
                <a href="{% url 'posts:update' post.id %}" class="btn  btn-secondary mt-3">Update</a>
            </div>
            {% endif %}
        </div>

    </div>

    <img style="width: 100%;" src="{{ post.picture.url }}" alt="{{ post.title }}">

    <p><strong>{{ post.resume }}</strong></p>

    <div class="d-grid">
        <a href="{% url 'posts:detail' post.id %}" class="btn btn-lg btn-secondary mt-5">Full Post</a> 
    </div>


</div>