blogpost/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Post urls."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/create',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='posts/<int:id>',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/<int:id>/delete',
        view=views.DeletePostView.as_view(),
        name='delete'
    ),
    path(
        route='posts/<int:id>/update',
        view=views.UpdatePostView.as_view(),
        name='update'
    ),
    path(
        route='posts/<int:id>/comments',
        view=views.AddCommentView.as_view(),
        name='comment'
    ),
    path(
        route='posts/<int:id>/like',
        view=views.LikeView,
        name='like'
    )
]

users/urls.py
"""users urls."""

# Django
from django.urls import path
from users import views

urlpatterns = [
     path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='signup/',
        view=views.SingUpView.as_view(),
        name='signup'
    ),
    path(
        route='<str:username>/profile',
        view=views.ProfileDetailView.as_view(),
        name='detail'
    ),
    path(
        route='<str:username>/profile/follow',
        view=views.FollowView,
        name='follow'
    ),
    path(
        route='explore/people',
        view=views.UsersToFollowView.as_view(),
        name='explore'
    ),
    path(
        route='me/update',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
    path(
        route='logout',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

templates/base.html
  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>
<body>

    {% include "nav.html" %}

    <div class="container mb-5 mt-5">
        {% block container %}
        {% endblock%}
    </div>
    
</body>
</html>

templates/footer.html
{% load static%}
<footer id="footer" class="pt-4">
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-12 col-lg">
                <a href="#">Preguntas frecuentes</a>
            </div>
            <div class="col-12 col-lg">
                <a href="#">Contactanos</a>
            </div>
            <div class="col-12 col-lg">
                <a href="#">Terminos y condiciones</a>
            </div>
            <div class="col-12 col-lg">
                <a href="#">Privacidad</a>
            </div>
        </div>
    </div>
</footer>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "images/logo.jpg" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'images/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "posts:create" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
                
                <li class="nav-item nav-icon">
                    <a href="{% url 'users:explore' %}">
                        <i class="fas fa-user-plus"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>