blogpost/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Post urls."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostFeedView.as_view(),
        name='feed'
    ),
    path(
        route='posts/create',
        view=views.CreatePostView.as_view(),
        name='create'
    ),
    path(
        route='posts/<int:id>',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
    path(
        route='posts/<int:id>/delete',
        view=views.DeletePostView.as_view(),
        name='delete'
    ),
    path(
        route='posts/<int:id>/update',
        view=views.UpdatePostView.as_view(),
        name='update'
    ),
    path(
        route='posts/<int:id>/comments',
        view=views.AddCommentView.as_view(),
        name='comment'
    ),
    path(
        route='posts/<int:id>/like',
        view=views.LikeView,
        name='like'
    )
]

users/urls.py
"""users urls."""

# Django
from django.urls import path
from users import views

urlpatterns = [
     path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='signup/',
        view=views.SingUpView.as_view(),
        name='signup'
    ),
    path(
        route='<str:username>/profile',
        view=views.ProfileDetailView.as_view(),
        name='detail'
    ),
    path(
        route='<str:username>/profile/follow',
        view=views.FollowView,
        name='follow'
    ),
    path(
        route='explore/people',
        view=views.UsersToFollowView.as_view(),
        name='explore'
    ),
    path(
        route='me/update',
        view=views.UpdateProfileView.as_view(),
        name='update'
    ),
    path(
        route='logout',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

users/models.py
"""Users models."""

# Django
from django.db import models

# Models
from django.contrib.auth.models import User

class Profile(models.Model):
    """Profile model holds the public information of the user."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    biography = models.TextField(max_length=500, blank=True)

    picture = models.ImageField(
        'profile image',
        upload_to='users/pictures/',
        blank=True,
        null=True
    )
    
    followers = models.PositiveIntegerField(default=0)
    blog_posted = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username
    

"""add follow field to user class dynamically"""
User.add_to_class('follow', models.ManyToManyField('self', related_name='following', symmetrical=False))

users/forms.py
"""Users forms."""

# Django
from django import forms

# Models 
from django.contrib.auth.models import User
from users.models import Profile

class SignUpForm(forms.Form):
    """Sign up form"""
    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(max_length=70, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput())

    first_name = forms.CharField(min_length=3)
    last_name = forms.CharField(min_length=3)

    email = forms.CharField(max_length=70, widget=forms.EmailInput())

    def clean_username(self):
        """User name must be unique."""

        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()

        if username_taken:
            raise forms.ValidationError('Sorry that username is already in use')
        return username

    def clean(self):
        """Verify that password mathcs."""
        data = super().clean()

        passwd = data['password']
        passwd_conf = data['password_confirmation']

        if passwd != passwd_conf:
            raise forms.ValidationError('Passwords does not match')
        return data

    def save(self):
        """Create user and profile."""

        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

class UpdateProfileForm(forms.ModelForm):
    """Update profile form."""

    class Meta:
        """Meta class."""
        model=Profile
        fields=(
            'user',
            'biography',
            'picture'
        )

users/views.py
"""Users views."""

# Django 
from django.urls import reverse, reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

# Views and auth_views
from django.contrib.auth import views as auth_views
from django.views.generic import (
    UpdateView,
    FormView,
    DetailView,
    ListView
)

# Forms
from users.forms import SignUpForm, UpdateProfileForm

# Models
from posts.models import Post
from users.models import Profile
from django.contrib.auth.models import User


class SingUpView(FormView):
    """Sing up view."""
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        #save form data
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """Login view."""
    template_name = 'users/login.html'

class LogoutView(auth_views.LogoutView):
    """Log out view."""
    template_name = 'users/logged_out.html'


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view. the users are redirect to this view
    if they do his first login."""

    template_name = 'users/update.html'
    model = Profile
    fields = ['picture', 'biography']
    context_object_name = 'profile'
    queryset = Profile.objects.all()

    def get_success_url(self):
        """Check if the user follow people. if the user follow other user,
        its redirect normaly to his own profile, if hes not follow someone
        its redirect to explore view to follow users, yes its work like a middleware""" 

        user = self.request.user
        follow_list = list(user.follow.all())
        if len(follow_list) == 0:
            return reverse_lazy('users:explore')
        else:
            return reverse('users:detail', kwargs={'username': user.username})

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        """Add user to the context."""
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user 
        return context
    

class ProfileDetailView(LoginRequiredMixin, DetailView):
    """Profile detail view."""

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context and check if the requesting user(user_from)
         already follows the user(user)"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        user_from = self.request.user

        follows = False
        if user_from.follow.filter(id=user.id).exists():
            follows = True

        context['follows'] = follows
        context['posts'] = Post.objects.filter(user=user).order_by('-created')
        return context

def FollowView(request, username):
    """Follow view. Chek if the requesting user(user_from) already
     follow the user(user_to) and add or substract 1 to followers counter 
     of the user."""

    user_to = get_object_or_404(User, username=request.POST.get('user_username'))
    user_from = request.user
    follows = False

    if user_from.follow.filter(id=user_to.id).exists():
        user_from.follow.remove(user_to)
        follows = False
        user_to.profile.followers -= 1
        user_to.profile.save()

    else:
        user_from.follow.add(user_to)
        follows = True
        user_to.profile.followers += 1
        user_to.profile.save()

    return HttpResponseRedirect(reverse('users:detail', kwargs={'username': request.POST.get('user_username')}))


class UsersToFollowView(LoginRequiredMixin, ListView):
    """Users to follow view, return all the users that the requesting
    user is not following."""

    template_name = 'users/new_folow.html'
    model = User
    ordering = ('-created',)
    paginate_by = 30
    context_object_name = 'users'

    def get_queryset(self):
        """return all users, excluding the users that the
        requesting user already follow."""

        user = self.request.user

        id_list = []
        follow_list = list(user.follow.all())

        for i in follow_list:
            id_list.append(i.id)
        id_list.append(user.id)
        
        return User.objects.exclude(id__in=id_list)
    

templates/users/base.html
  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static 'images/logo.jpg' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | .Blog</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">

            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username}}"
                    class="rounded-circle"
                    width="220px"
                />
            </div>

            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Edit profile
                        </a>
                    {% else %}
                    <form action="{% url 'users:follow' user.username %}" method="POST">
                        {% csrf_token %}

                        <button class="btn btn-lg btn-secondary mt-5 " type="submit" name="user_username" value="{{ user.username }}">
                            {% if follows %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>

                    </form>
                    {% endif %}
                </h2>

                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.blog_posted }}</b> Posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}</b> Followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.get_full_name }}</b> 
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pe-5 ps-5 d-flex justify-content-center align-items-center">
                <div class="card" style="width: 18rem;">
                    <a href="{% url 'posts:detail' post.id %}">
                        <img src="{{ post.picture.url }}" class="card-img-top" alt="{{ post.title }}">
                    </a>
                    <div class="card-body">
                      <h5 class="card-title">{{ post.title }}</h5>
                      <p class="card-text">{{ post.resume }}</p>
                      
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>BlogPost | sign in</title>
{% endblock%}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </p>
    {% endif%}

    <form method="POST" action="{% url "users:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-group mt-4">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>

        <div class="d-grid">
            <button class="btn btn-lg btn-secondary mt-5" type="submit">Sign in!</button>
        </div>

        <p class="mt-4">You dont have an acoount yet? <a href="{% url 'users:signup' %}">SignUp here uwu</a></p>
    </form>

{% endblock %}

templates/users/new_folow.html
{% extends "base.html" %}

{% block head_content %}
    <title>BlogPost</title>
{% endblock%}

{% block container %}

    <div class="container">
        <div class="row">

            {% for user in users %}
                {% include "users/user_card.html" %}
            {% endfor %}
        </div>
    </div>



{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>BlogPost | Signup</title>
{% endblock %}

{% block container %}


    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {# username field #}
            <div class="form-group">
                <input
                    class="form-control {% if form.username.errors %}is-invalid{% endif %}"
                    type="text"
                    name="username"
                    placeholder="username"
                    value="{% if form.errors %}{{ form.username.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}{{ error }}{% endfor %}
                </div>
            </div>

            {# password_field field #}
            <div class="form-group mt-4">
                <input
                    class="form-control {% if form.password.errors %}is-invalid{% endif %}"
                    type="password"
                    name="password"
                    placeholder="password"
                    value="{% if form.errors %}{{ form.password.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}{{ error }}{% endfor %}
                </div>
            </div>

             {# password_confirmation field #}
             <div class="form-group mt-4">
                <input
                    class="form-control {% if form.password_confirmation.errors %}is-invalid{% endif %}"
                    type="password"
                    name="password_confirmation"
                    placeholder="password confirmation"
                    value="{% if form.errors %}{{ form.password_confirmation.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.password_confirmation.errors %}{{ error }}{% endfor %}
                </div>
            </div>

            {# first_name field #}
            <div class="form-group mt-4">
                <input
                    class="form-control {% if form.first_name.errors %}is-invalid{% endif %}"
                    type="text"
                    name="first_name"
                    placeholder="First name"
                    value="{% if form.errors %}{{ form.first_name.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.first_name.errors %}{{ error }}{% endfor %}
                </div>
            </div>

            {# last_name field #}
            <div class="form-group mt-4">
                <input
                    class="form-control {% if form.last_name.errors %}is-invalid{% endif %}"
                    type="text"
                    name="last_name"
                    placeholder="Last name"
                    value="{% if form.errors %}{{ form.last_name.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.last_name.errors %}{{ error }}{% endfor %}
                </div>
            </div>


            {# Email field #}
            <div class="form-group mt-4">
                <input
                    class="form-control {% if form.email.errors %}is-invalid{% endif %}"
                    type="text"
                    name="email"
                    placeholder="Email"
                    value="{% if form.errors %}{{ form.email.value }}{% endif %}"
                >
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}{{ error }}{% endfor %}
                </div>
            </div>


            <div class="d-grid">
                <button class="btn btn-lg btn-secondary mt-5" type="submit">Sign Up!</button>
            </div>

        <p class="mt-4">You already have an acoount? <a href="{% url 'users:login' %}">Sign in here uwu</a></p>


    </form>


{% endblock %}

templates/users/update.html
{% extends "base.html" %}

{% block head_content %}
    <title>BlogPost | Update</title>
{% endblock %}

{% block container %}
    <form class="mt-5" action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <input type="hidden" name="user" value="{{ user.pk}}" />

        {# picture input #}
        <div class="form-group">
            <label for="formFile" class="form-label">Choose your photo</label>
            <input class="form-control" type="file" name="picture">
        </div>

        {# biography input #}
        <div class="form-group mt-4">
            <label for="exampleFormControlTextarea1" class="form-label">biography</label>
            <textarea class="form-control" name="biography">{{ form.biography.value }}</textarea>
        </div>

        <div class="d-grid">
            <button class="btn btn-lg btn-secondary mt-5" type="submit">Update</button>
        </div>
    </form>
{% endblock %}

templates/users/user_card.html
{% load static %}
<a href="{% url "users:detail" user.username %}" style="text-decoration: none; color: black;">
    <div class="card mt-5 mb-3" style="border: 1px solid #bfbdc1;" >
    <div class="row g-0">
        <div class="col-md-4">
        
            {% if user.profile.picture %}
            <img class=" pt-1 rounded-circle" height="150" src="{{ user.profile.picture.url }}" alt="{{ user.get_full_name }}">
            {% else %}
            <img src="{% static 'images/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
            {% endif %}
        
        </div>
        <div class="col-md-8">
        <div class="card-body">
            <h5 class="card-title">{{ user.get_full_name }}</h5>
            <p class="card-text">{{ user.profile.biography }}</p>
            
        </div>
        </div>
    </div>
    </div>
</a>  